require 'active_record'
require 'require_all'
require 'yaml'

namespace :db do

  db_config       = YAML::load(File.open('config/database.yml'))
  db_config_admin = db_config

  desc "Migrate the database"
  task :migrate do
    ActiveRecord::Base.establish_connection(db_config)
    ActiveRecord::Migrator.migrate("db/migrate/")
    puts "Database migrated."
  end

  desc "Seed the database"
  task :seed do
    ActiveRecord::Base.establish_connection(db_config_admin)
    require_all "models/*.rb"
    require_relative "db/seeds.rb"
    puts "Database seeded"
  end

  desc "Drop the database"
  task :drop do
    ActiveRecord::Base.establish_connection(db_config_admin)
    ActiveRecord::Base.connection.drop_database(db_config["database"])
    puts "Database deleted."
  end
end
